#!/usr/bin/env bash

for f in $(ls ~/.ssh/*.template); do
    op inject -i $f -o ~/.ssh/$(basename $f .template)
done

terraform "$@"

for f in $(ls ~/.ssh/*.template); do
    rm ~/.ssh/$(basename $f .template)
done
