[settings]
trusted_config_paths = [
  '~/private/Dev',
  '~/.mise.toml'
]

[env]
DOCKER_CONTEXT = 'orbstack'

[tools]
rust      = '1.74.0'
golang    = '1.21.1'
nodejs    = '20.7.0'
bun       = '1.0.4'
pnpm      = '8.8.0'
ruby      = '3.2.2'
yarn      = '1.22.19'
python    = '3.11.5'
terraform = '1.4.7'

[plugins]
bun       = 'https://github.com/cometkim/asdf-bun.git'
go        = 'https://github.com/rtx-plugins/rtx-golang.git'
pnpm      = 'https://github.com/jonathanmorley/asdf-pnpm.git'
ruby      = 'https://github.com/asdf-vm/asdf-ruby'
rust      = 'https://github.com/code-lever/asdf-rust.git'
terraform = 'https://github.com/asdf-community/asdf-hashicorp.git'
yarn      = 'https://github.com/twuni/asdf-yarn.git'
